### ISSUE TITLE
✨ feat: 백그라운드 사용자 위치 전송

### ISSUE THREAD

**Issue by k-oyun** [WaitherTeam/Waither-FE#105]
# Title

- 사용자 위치 전송

# TODO

- [x] 사용자 위치 받아오기
- [x] 백그라운드 설정
- [x] 백그라운드 스케쥴러 설정
- [x] 알림 설정 화면에서 사용자가 직접 선택한 시간에 사용자 위치를 서버로 전송
- [x] 사용자에게 기상특보 전송을 위해 30분마다 사용자 위치를 서버로 전송

# etc

- 없습니다
