### ISSUE TITLE
✨ feat: 비밀번호 재설정 화면 구성

### ISSUE THREAD

**Issue by yeopyeop-82** [WaitherTeam/Waither-FE#28]
# Title

- 숨쉬기 기능 개발

# TODO

- [x] settings-info-pw1
- [x] settings-info-pw2
- [x] settings-info-pw3
- [x] settings-info-pw4
- [x] settings-info-pw5
- [x] settings-info-pw6

# etc

- 아직 링크가 따로 없는 화면.. 접근 불가능
- 화면을 당장 볼 수 없으니 원하는 곳에 접근 링크 임시로 달고 작업해주세요 !
- ex) 로그인 화면에 비밀번호 재설정 버튼 만들기 (임시로 ..)
