### ISSUE TITLE
🐛 fix: 회원가입 화면 이메일 입력 버그 수정

### ISSUE THREAD

**Issue by k-oyun** [WaitherTeam/Waither-FE#32]
# Title

- 회원가입 화면 이메일 입력 버그 수정

# TODO

- [x] 이메일 중복이 아니면서 이메일 형식에 맞는 경우에만 중복 확인 가능하게 수정 
- [x] 이메일이 중복인 경우 Error Image 및 Message 색상이 red color로 고정되는 부분 수정 
- [x] 이메일 중복인 경우 border-bottom 색상 오류 수정 -> 오류가 아닌 디자인적 요소이기에 회의 필요
- [x] button disabled
# etc

- 이메일 중복인 경우에는 다음 단계로 넘어갈 수 없지만 중복이 되지만 않으면 이메일 형식에 맞지 않아도 다음 단계로 넘어감

**Comment by yeopyeop-82** [comment]
내일 저도 코드 확인해볼게요 !!
