### ISSUE TITLE
✨ feat: 메인화면 커스텀 여부 API 연결

### ISSUE THREAD

**Issue by k-oyun** [WaitherTeam/Waither-FE#78]
# Title

- 메인화면 날씨 상세 정보 API 연결

# TODO

- [x] 강수량 보기 API 호출
- [x] 풍량, 풍속 보기 API 호출
- [x] 미세먼지 보기 API 호출

# etc

- 없습니다
