### ISSUE TITLE
✨ feat: 알림 설정 API 연결

### ISSUE THREAD

**Issue by k-oyun** [WaitherTeam/Waither-FE#79]
# Title

- 알림 설정 API 연결

# TODO

- [x] 선택 요일 API 호출
- [x] 선택 시간대 API 호출
- [x] 외출 시간 알림 여부 API 호출
- [x] 기상 특보 알림 여부 API 호출
- [x] 사용자 맞춤 예보 여부 API 호출
- [x] 강설 정보 여부 API 호출
- [x] 바람 세기 알림 여부 API 호출
- [x] 선택된 바람 세기 API 호출

# etc

- 없습니다
